[2015-10-18 11:57:12] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:57:12] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:06] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:06] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:08] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#17 {main}  
[2015-10-18 11:58:09] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/ce/sites/new/bootstrap/cache/compiled.php:6993
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1283): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('encrypter', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(1328): Illuminate\Foundation\Application->make('Illuminate\Cont...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(1312): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(1298): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Middle...', Array)
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Middle...', Array)
#8 /home/ce/sites/new/bootstrap/cache/compiled.php(2257): Illuminate\Foundation\Application->make('App\Http\Middle...')
#9 /home/ce/sites/new/index.php(58): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main}  
[2015-10-18 14:12:52] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:22:21] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:26:56] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:27:00] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:52:28] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin/AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:47] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:49] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:50] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:50] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:50] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
[2015-10-18 14:53:50] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\AdminController does not exist' in /home/ce/sites/new/bootstrap/cache/compiled.php:1285
Stack trace:
#0 /home/ce/sites/new/bootstrap/cache/compiled.php(1285): ReflectionClass->__construct('App\Http\Contro...')
#1 /home/ce/sites/new/bootstrap/cache/compiled.php(1236): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#2 /home/ce/sites/new/bootstrap/cache/compiled.php(1774): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#3 /home/ce/sites/new/bootstrap/cache/compiled.php(8878): Illuminate\Foundation\Application->make('App\Http\Contro...')
#4 /home/ce/sites/new/bootstrap/cache/compiled.php(8867): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#5 /home/ce/sites/new/bootstrap/cache/compiled.php(7825): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'login')
#6 /home/ce/sites/new/bootstrap/cache/compiled.php(7796): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#7 /home/ce/sites/new/bootstrap/cache/compiled.php(7449): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/ce/sites/new/bootstrap/cache/compiled.php(7450): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/ce/sites/new/bootstrap/cache/compiled.php(7438): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 /home/ce/sites/new/bootstrap/cache/compiled.php(7423): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /home/ce/sites/new/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 /home/ce/sites/new/bootstrap/cache/compiled.php(9547): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/ce/sites/new/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#21 /home/ce/sites/new/bootstrap/cache/compiled.php(12867): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#24 /home/ce/sites/new/bootstrap/cache/compiled.php(11490): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#27 /home/ce/sites/new/bootstrap/cache/compiled.php(12608): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#30 /home/ce/sites/new/bootstrap/cache/compiled.php(12547): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#33 /home/ce/sites/new/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/ce/sites/new/bootstrap/cache/compiled.php(9539): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/ce/sites/new/bootstrap/cache/compiled.php(9529): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/ce/sites/new/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/ce/sites/new/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 /home/ce/sites/new/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 {main}  
